before_commands:
    - "composer install --prefer-source"

inherit: true
filter:
    paths:
        - src

tools:
    php_code_sniffer:
        enabled:              true
        command:              phpcs
        config:
            standard:         PSR2

    php_cs_fixer:
        enabled:              true
        config:
            level:            psr2

    php_mess_detector:
        enabled:              true
        command:              phpmd
        config:
            rulesets:
                - codesize
                - unusedcode
                - naming
                - design
                - controversial

    php_pdepend:
        enabled:              true
        command:              pdepend

    php_analyzer:
        enabled:              true

    sensiolabs_security_checker: true
