language: php

php:
  - 7.2

env:
  - DB=mysql

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

script: phpunit --configuration phpunit.xml --coverage-text