language: php

php:
  - 7.2

env:
  - DB=mysql

before_script:
  - mkdir config
  - touch config/.config
  - composer self-update
  - composer install --prefer-source --no-interaction

script: phpunit --configuration phpunit.xml --coverage-text